#' Read Sma3s Annotation TSV File
#'
#' Reads the tab-separated annotation file generated by the Sma3s program.
#' The file contains functional annotations for each protein sequence in a proteome.
#'
#' @param sma3sAnnotationPath Character string. Path to the Sma3s TSV annotation file.
#'
#' @return A data frame with 14 columns:
#'   \item{fastaheader}{Full FASTA header from the sequence file}
#'   \item{genename}{Gene name from the annotation}
#'   \item{genedescription}{Functional description of the gene product}
#'   \item{enzyme}{EC numbers (semicolon-separated)}
#'   \item{goc}{Gene Ontology Cellular Component IDs (semicolon-separated)}
#'   \item{gocname}{GO Cellular Component names}
#'   \item{gof}{Gene Ontology Molecular Function IDs (semicolon-separated)}
#'   \item{gofname}{GO Molecular Function names}
#'   \item{gop}{Gene Ontology Biological Process IDs (semicolon-separated)}
#'   \item{gopname}{GO Biological Process names}
#'   \item{keyword}{UniProt keywords (semicolon-separated)}
#'   \item{pathway}{Pathway annotations (semicolon-separated)}
#'   \item{goslim}{GO Slim terms (semicolon-separated)}
#'   \item{fastashortheader}{Short FASTA header (first word after ">")}
#'
#' @examples
#' \dontrun{
#' annot_df <- readSma3sAnnotation("path/to/annotation.tsv")
#' head(annot_df)
#' }
#'
#' @export
readSma3sAnnotation<-function(sma3sAnnotationPath){
    sma3sAnnotationDf<-read.csv(sma3sAnnotationPath,
                                col.names=c("fastaheader",
                                            "genename",
                                            "genedescription",
                                            "enzyme",
                                            "goc",
                                            "gocname",
                                            "gof",
                                            "gofname",
                                            "gop",
                                            "gopname",
                                            "keyword",
                                            "pathway",
                                            "goslim"),
                                colClasses=rep("character",13),
                                quote="",
                                header=FALSE,
                                sep="\t",
                                comment.char="#",
                                stringsAsFactors = FALSE)
    fastaShortHeaderVec<-gsub("^([^ ]+) .*$","\\1",sma3sAnnotationDf[,"fastaheader"])
    sma3sAnnotationDf[,"fastashortheader"]<-fastaShortHeaderVec ; rm(fastaShortHeaderVec)
    sma3sAnnotationDf
}
